name = "Zola Tailwind"
description = "A Zola theme using Tailwindcss"
license = "MIT"
homepage = "https://github.com/tchartron/zola-tailwind"
# The minimum version of Zola required
min_version = "0.9.0"
# An optional live demo URL
demo = ""

# The theme author info: you!
[author]
name = "Thomas Chartron"
homepage = "https://tchartron.com"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
# [original]
# author =  "mdo"
# homepage = "https://markdotto.com/"
# repo = "https://www.github.com/mdo/hyde"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
zt.enable_search = true
zt.enable_adsense = true
zt.adsense_link = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=myclientid"

zt.navbar_items = [
    { code = "en", nav_items = [
        { url = "$URL/", name = "Home" },
        { url = "$URL/categories", name = "Categories" },
        { url = "$URL/tags", name = "Tags" },
    ] },
    { code = "fr", nav_items = [
        { url = "$URL/", name = "Accueil" },
        { url = "$URL/categories", name = "Categories" },
        { url = "$URL/tags", name = "Tags" },
    ] },
]

zt.navbar_title = "title"

# Index page
[extra.index]
title = "Main title"
image = "https://via.placeholder.com/200"

[extra.default_author]
name = "John Doe"
avatar = "https://via.placeholder.com/200"

[extra.social]
github = "https://github.com/johndoe"
gitlab = "https://gitlab.com/johndoe"
twitter = "https://twitter.com/johndoe"
linkedin = "https://www.linkedin.com/in/john-doe-b1234567/"
email = "john.doe@gmail.com"
